### ISSUE TITLE
Question: How do you monitor for new instantiations of GameObjects?

### ISSUE THREAD

**Issue by adscott1982** [tharinga/UniMediator#1]
This is a very cool library. I have been reading through the code though and I don't currently see where you attach to newly created game objects. How is that done? (is it done?)

I can see the ScanScene method, and how it loops through all the currently active monobehaviours and adds them to the list, but I can't find anything that listens for new object instantiations in the active scene.

**Comment by tharinga** [comment]
When instantiating a new object in an active scene you can add it by calling `Mediator.AddMediatedObject(MonoBehaviour monoBehaviour)`

**Comment by adscott1982** [comment]
Thank you!
